services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=${DB_USERNAME?Variable not set}
      - POSTGRES_PASSWORD=${DB_PASSWORD?Variable not set}
      - POSTGRES_DB=account-${DB_NAME?Variable not set}
    volumes:  
    - pgdata:/var/lib/postgresql/data
    ports:
    - 5432:5432

  redis:
    image: "redis:alpine"
    command: redis-server
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/var/lib/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_REPLICATION_MODE=master

  account-service:
    build: 
      context: ./account-service
      dockerfile: Dockerfile
    image: account-service
    container_name: account-service
    ports:
      - "8000:8000"
    volumes:
      - ./account-service:/app
    environment:
      - DB_NAME=${DB_NAME?Variable not set}
      - DB_USERNAME=${DB_USERNAME?Variable not set}
      - DB_PASSWORD=${DB_PASSWORD?Variable not set}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT?Variable not set}
      - LOG_LEVEL=${LOG_LEVEL?Variable not set}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT?Variable not set}
      - REDIS_KEY=${REDIS_KEY?Variable not set}
      - REDIS_DB=${REDIS_DB?Variable not set}
      - OTEL_PYTHON_LOG_CORRELATION=true
      - OTEL_PYTHON_LOG_FORMAT="%(msg)s [span_id=%(span_id)s]"
      - OTEL_PYTHON_LOG_LEVEL=info
      - OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED=true
      - OTEL_EXPORTER_OTLP_TRACES_INSECURE=true
    depends_on:
      - postgres
      - redis
    restart: always
    
  journal-service:
    build: 
      context: ./journal-service
      dockerfile: Dockerfile
    image: journal-service
    container_name: journal-service
    ports:
      - "8001:8001"
    volumes:
      - ./journal-service:/app
    environment:
      - DB_NAME=${DB_NAME?Variable not set}
      - DB_USERNAME=${DB_USERNAME?Variable not set}
      - DB_PASSWORD=${DB_PASSWORD?Variable not set}
      - DB_HOST=postgres
      - DB_PORT=${DB_PORT?Variable not set}
      - LOG_LEVEL=${LOG_LEVEL?Variable not set}
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT?Variable not set}
      - REDIS_KEY=${REDIS_KEY?Variable not set}
      - REDIS_DB=${REDIS_DB?Variable not set}
    depends_on:
      - postgres
      - account-service
    restart: always

  jaeger:
    image: jaegertracing/all-in-one
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317" 
      - "4318:4318" 
      - "9411:9411"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    depends_on:
      - account-service
      - journal-service
      - redis
volumes:
  pgdata: